- name: copy the rabbitmq repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Installing rabbitmq
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: enable, start the service
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes
    state: restarted

- name: create and provide permissions to user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present