- name: install mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: enable, start the service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: restarted

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1