- name: create system user
  ansible.builtin.user:
    name: RoboShop
    system: true
    comment: Roboshop system user
    shell: /sbin/nologin
    home: /app

- name: Remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: delete {{ component }} file
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

- name: Download {{ component }} application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    path: /tmp/{{ component }}.zip

- name: Extract {{ component }} application 
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes